name: Build
on: [push, pull_request]

jobs:
  build-android:
    name: Android
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with: 
        flutter-version: '3.10.x'

    - name: Setup Android NDK
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25
        add-to-path: true
    
    - name: Add NDK to ENV
      run: |
        export ANDROID_NDK_HOME="${{ steps.setup-ndk.outputs.ndk-path }}"

    - name: Setup signing
      env:
        KEY_JKS: ${{ secrets.KEY_JKS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      run: |
        echo "$KEY_JKS" | base64 -d > android/key.jks
        echo "storePassword=$STORE_PASSWORD" >> android/key.properties
        echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
        echo "keyAlias=$KEY_ALIAS" >> android/key.properties
        echo "storeFile=`pwd`/android/key.jks" >> android/key.properties

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y lld autogen libasound2-dev pkg-config make libssl-dev gcc g++ curl wget git libwebkit2gtk-4.1-dev


    - name: Install tools
      run: |
        rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
        cargo install flutter_rust_bridge_codegen
        cargo install cargo-ndk
        cargo install cargo-expand

    - name: Build dependencies
      run: |
        flutter pub get
        chmod +x build.sh
        ./build.sh

    - name: Build APK
      run: |
        flutter build apk --release --split-per-abi
    
    - name: Upload arm64
      uses: actions/upload-artifact@v3
      with:
        name: onetagger-android-arm64
        path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

    - name: Upload arm32
      uses: actions/upload-artifact@v3
      with:
        name: onetagger-android-arm32
        path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

    - name: Upload x86_64
      uses: actions/upload-artifact@v3
      with:
        name: onetagger-android-x86_64
        path: build/app/outputs/flutter-apk/app-x86_64-release.apk
